# Generated by Django 3.2.8 on 2021-11-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app12', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Password',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Place',
            field=models.CharField(default='', max_length=20),
        ),
    ]
